# Generated by Django 3.2.5 on 2021-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_Name', models.CharField(max_length=30)),
                ('new_Age', models.PositiveIntegerField()),
                ('new_Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
