# Generated by Django 3.2.5 on 2021-07-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210719_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='ageee',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='eeemail',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='nameee',
        ),
    ]
