# Generated by Django 3.2.5 on 2021-07-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210722_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='car',
            new_name='newCar',
        ),
    ]
